/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
  api(libs.com.google.dagger.dagger)
  api(project(":annotation"))
  api(project(":commons"))
  api(libs.org.slf4j.slf4j.api)
  annotationProcessor(project(":generator"))

  testImplementation(libs.org.assertj.assertj.core)
  testImplementation(libs.org.junit.jupiter.junit.jupiter)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
  testRuntimeOnly(libs.org.junit.platform.junit.platform.launcher)
}

description = "aop"
