/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
  api(libs.com.google.googlejavaformat.google.java.format)
  api(libs.com.palantir.javapoet.javapoet)
  api(project(":annotation"))
  api(project(":commons"))
  api(libs.jakarta.annotation.jakarta.annotation.api)

  compileOnly(libs.org.slf4j.slf4j.simple)
  compileOnly(libs.com.google.auto.value.auto.value.annotations)
  implementation(libs.com.google.auto.value.auto.value.processor)

  testImplementation(libs.compile.testing)
  testImplementation(libs.org.assertj.assertj.core)
  testImplementation(libs.org.junit.jupiter.junit.jupiter)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
  testRuntimeOnly(libs.org.junit.platform.junit.platform.launcher)
}

tasks.withType<JavaCompile>().configureEach { options.compilerArgs.add("-proc:none") }

description = "generator"
