/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
    api(project(":annotation"))
    api(project(":logging"))
    api(project(":txmanager:platform"))
}

description = "agent-example"
