/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "codegen-parent"

// Include the shared core library and the Gradle plugin as composite builds.
// This makes:
//   - "github.benslabbert.vdw.codegen:advice-extractor-core" available for subproject deps.
//   - plugin id "github.benslabbert.vdw.codegen.merge-advices" available in plugins {} blocks.
includeBuild("advice-extractor-core")

includeBuild("advice-extractor-gradle-plugin")

include(":aop")

include(":logging")

include(":advice-transformer")

include(":config")

include(":generator")

include(":txmanager:agent")

include(":txmanager:agent-example")

include(":txmanager:platform")

include(":txmanager:plugin-example")

include(":annotation")

include(":commons")

include(":launcher")

include(":example")

include(":advice-extractor-maven-plugin")

include(":commons-test")
