/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "codegen-parent"

include(":aop")

include(":logging")

include(":bom")

include(":advice-transformer")

include(":config")

include(":generator")

include(":txmanager:agent")

include(":txmanager:agent-example")

include(":txmanager:platform")

include(":txmanager:plugin-example")

include(":annotation")

include(":commons")

include(":launcher")

include(":example")

include(":advice-extractor-plugin")

include(":commons-test")
