/* Licensed under Apache-2.0 2025. */
package github.benslabbert.vdw.codegen.maven.plugin;

import github.benslabbert.vdw.codegen.extractor.core.AdviceMerger;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.apache.maven.artifact.Artifact;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;

/**
 * Extracts all {@code META-INF/advice_annotations} files from dependency JARs and merges them with
 * the annotation-processor-generated file for the current module into a single, deduplicated file.
 * Runs after compilation to capture files generated by annotation processors.
 */
@Mojo(
    name = "merge-advices",
    defaultPhase = LifecyclePhase.PROCESS_CLASSES,
    requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME)
public class MergeAdvicesMojo extends AbstractMojo {

  @Parameter(defaultValue = "${project}", readonly = true, required = true)
  private MavenProject project;

  @Parameter(defaultValue = "${project.build.outputDirectory}/META-INF", readonly = true)
  private File outputDirectory;

  @Parameter(property = "mergedAdviceAnnotations", defaultValue = "advice_annotations")
  private String adviceAnnotations;

  public void execute() throws MojoExecutionException {
    getLog().info("==========================================");
    getLog().info("Starting advice file extraction and merge");
    getLog().info("==========================================");

    // The AP writes its output to outputDirectory/adviceAnnotations during compile.
    File apOutputFile = new File(outputDirectory, adviceAnnotations);

    List<File> jarFiles = collectDependencyJars();
    getLog().info("Found " + jarFiles.size() + " dependency JAR files to scan");

    LinkedHashSet<String> entries = AdviceMerger.merge(apOutputFile, jarFiles, adviceAnnotations);

    if (entries.isEmpty()) {
      getLog().warn("No advice entries found in current module or dependencies!");
    } else {
      getLog().info("Total " + entries.size() + " unique advice entries found");
    }

    writeMergedFile(entries);

    getLog().info("==========================================");
    getLog().info("Advice merge completed successfully");
    getLog().info("==========================================");
  }

  /** Collects all dependency JAR files from the project. */
  private List<File> collectDependencyJars() {
    List<File> jarFiles = new ArrayList<>();
    Set<Artifact> artifacts = project.getArtifacts();

    if (artifacts != null) {
      for (Artifact artifact : artifacts) {
        if ("jar".equals(artifact.getType()) && artifact.getFile() != null) {
          jarFiles.add(artifact.getFile());
        }
      }
    }

    return jarFiles;
  }

  /** Writes the merged, deduplicated content to the output file, replacing any existing content. */
  private void writeMergedFile(LinkedHashSet<String> entries) throws MojoExecutionException {
    if (!outputDirectory.exists()) {
      if (!outputDirectory.mkdirs()) {
        throw new MojoExecutionException(
            "Failed to create output directory: " + outputDirectory.getAbsolutePath());
      }
    }

    File mergedFile = new File(outputDirectory, adviceAnnotations);

    try {
      Files.writeString(mergedFile.toPath(), AdviceMerger.format(entries));
      getLog().info("Merged advices written to: " + mergedFile.getAbsolutePath());
    } catch (IOException e) {
      throw new MojoExecutionException(
          "Failed to write merged file: " + mergedFile.getAbsolutePath(), e);
    }
  }
}
