/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
  api(libs.ch.qos.logback.logback.classic)
  api(libs.org.slf4j.slf4j.api)
}

description = "logging"
