/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
    api(project(":logging"))
    api(libs.io.micrometer.micrometer.registry.jmx)
    api(libs.io.vertx.vertx.core)
    api(libs.io.vertx.vertx.launcher.application)
    api(libs.io.vertx.vertx.micrometer.metrics)
    api(libs.io.vertx.vertx.opentelemetry)
    runtimeOnly(libs.io.netty.netty.transport.native.epoll)
}

description = "launcher"
