/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
    api(libs.com.google.dagger.dagger)
    api(libs.com.google.dagger.dagger.compiler)
    api(libs.com.google.errorprone.error.prone.annotations)
    api(libs.com.google.guava.guava)
    api(libs.com.zaxxer.hikaricp)
    api(libs.commons.dbutils.commons.dbutils)
    api(project(":annotation"))
    api(project(":txmanager:platform"))
    api(libs.io.vertx.vertx.core)
    api(libs.io.vertx.vertx.json.schema)
    api(libs.io.vertx.vertx.pg.client)
    api(libs.io.vertx.vertx.service.proxy)
    api(libs.io.vertx.vertx.web)
    api(libs.jakarta.annotation.jakarta.annotation.api)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.glassfish.expressly.expressly)
    api(libs.org.hibernate.validator.hibernate.validator)
    api(libs.org.jooq.jooq)
    api(libs.org.slf4j.slf4j.api)
    testImplementation(libs.io.vertx.vertx.junit5)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testRuntimeOnly(libs.org.junit.platform.junit.platform.launcher)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.postgresql.postgresql)
    testImplementation(libs.org.slf4j.slf4j.simple)
    compileOnly(libs.com.google.auto.value.auto.value.annotations)
    annotationProcessor(libs.com.google.dagger.dagger.compiler)
}

description = "commons"
