/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
  compileOnly(libs.org.apache.maven.maven.core)
  compileOnly(libs.org.apache.maven.maven.plugin.api)
  compileOnly(libs.org.apache.maven.plugin.tools.maven.plugin.annotations)
}

description = "advice-extractor-plugin"
