/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
    api(project(":annotation"))
    api(libs.io.vertx.vertx.core)
    api(libs.jakarta.annotation.jakarta.annotation.api)
    compileOnly(libs.com.google.auto.value.auto.value.annotations)

    annotationProcessor(project(":generator"))
    annotationProcessor(libs.com.google.auto.value.auto.value.processor)
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-parameters")
    options.compilerArgs.add("-proc:full")
}

description = "config"
