/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
  api(libs.com.fasterxml.jackson.core.jackson.databind)
  api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
  api(libs.com.microsoft.playwright.playwright)
  api(libs.commons.codec.commons.codec)
  api(project(":commons"))
  api(project(":config"))
  api(project(":logging"))
  api(libs.io.rest.assured.rest.assured) {
    // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see:
    // https://docs.gradle.org/9.4.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
    exclude(mapOf("group" to "commons-codec", "module" to "commons-codec"))
  }
  api(libs.org.mockito.mockito.core)
  api(libs.org.testcontainers.testcontainers)
  api(libs.org.testcontainers.testcontainers.junit.jupiter)
  api(libs.org.testcontainers.testcontainers.postgresql)

  testImplementation(libs.compile.testing)
  testImplementation(libs.io.vertx.vertx.junit5)
  testImplementation(libs.org.assertj.assertj.core)
  testImplementation(libs.org.junit.jupiter.junit.jupiter)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
  testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
  testRuntimeOnly(libs.org.junit.platform.junit.platform.launcher)
}

description = "commons-test"
