/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":txmanager:agent"))
    api(project(":aop"))
    api(libs.net.bytebuddy.byte.buddy)
    api(libs.net.bytebuddy.byte.buddy.dep)
    api(libs.org.ow2.asm.asm)
    api(libs.org.slf4j.slf4j.api)
}

description = "advice-transformer"
