/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.java-conventions") }

dependencies {
    api(project(":advice-transformer"))
    api(project(":annotation"))
    api(project(":aop"))
    api(project(":commons"))
    api(project(":commons-test"))
    api(project(":config"))
    api(project(":generator"))
    api(project(":launcher"))
    api(project(":logging"))
    api(project(":txmanager:agent"))
    api(project(":txmanager:platform"))
}

description = "bom"
