/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.jakarta.annotation.jakarta.annotation.api)
}

description = "annotation"
